namespace RMAZOR.Models
{
    public enum EInputCommand
    {
        MoveUp,
        MoveDown,
        MoveLeft,
        MoveRight,
        RotateClockwise,
        RotateCounterClockwise,
        LoadCurrentLevel,
        LoadFirstLevelFromCurrentGroup,
        LoadNextLevel,
        ReadyToStartLevel,
        StartOrContinueLevel,
        FinishLevel,
        ReadyToUnloadLevel,
        UnloadLevel,
        PauseLevel,
        UnPauseLevel,
        KillCharacter,
        LoadRandomLevel,
        ShopMenu,
        SettingsMenu,
        RateGamePanel,
        LoadRandomLevelWithRotation,
        LoadLevelByIndex,
        LoadFirstLevelFromRandomGroup,
        EnableDebug,
        DisableDebug
    }
}