// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayGameResources
{
        public const string achievement_300_levels_finished = "CgkI1IvonNkDEAIQCg"; // <GPGSID>
        public const string leaderboard_level = "CgkI1IvonNkDEAIQBg"; // <GPGSID>
        public const string achievement_50_levels_finished = "CgkI1IvonNkDEAIQCA"; // <GPGSID>
        public const string achievement_800_levels_finished = "CgkI1IvonNkDEAIQDw"; // <GPGSID>
        public const string achievement_600_levels_finished = "CgkI1IvonNkDEAIQDQ"; // <GPGSID>
        public const string achievement_10_levels_finished = "CgkI1IvonNkDEAIQBQ"; // <GPGSID>
        public const string achievement_200_levels_finished = "CgkI1IvonNkDEAIQCQ"; // <GPGSID>
        public const string achievement_500_levels_finished = "CgkI1IvonNkDEAIQDA"; // <GPGSID>
        public const string achievement_400_levels_finished = "CgkI1IvonNkDEAIQCw"; // <GPGSID>
        public const string achievement_700_levels_finished = "CgkI1IvonNkDEAIQDg"; // <GPGSID>
        public const string achievement_900_levels_finished = "CgkI1IvonNkDEAIQEA"; // <GPGSID>
        public const string achievement_1000_levels_finished = "CgkI1IvonNkDEAIQEQ"; // <GPGSID>
        public const string achievement_100_levels_finished = "CgkI1IvonNkDEAIQBw"; // <GPGSID>
        public const string achievement_25_levels_finished = "CgkI1IvonNkDEAIQEg"; // <GPGSID>

}

